Copyright (C) 2018 Software Platform Lab, Seoul National University

Licensed under the Apache License, Version 2.0 (the "License"); 

you may not use this file except in compliance with the License. 

You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 

Unless required by applicable law or agreed to in writing, software 

distributed under the License is distributed on an "AS IS" BASIS, 


WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 


See the License for the specific language governing permissions and


limitations under the License.

**Colab 101**

Colab is a free Jupyter notebook environment offered by Google Research. 

**TensorFlow Practice Session**

>[3-1. TensorFlow Ops](#scrollTo=Ki_RHIwPJvyn)

>>[Graph and Session](#scrollTo=s97fwEOoiXk3)

>>[Constant op](#scrollTo=V5N1npMVQqJz)

>>[Math ops](#scrollTo=xrE4WkZNUn9o)

>>[*Quiz 1](#scrollTo=cnNhG69dgWsA)

>>[Variables](#scrollTo=a4UKKwwsZa4I)

>>>[Creating variables](#scrollTo=2TubsFPeZ0Rz)

>>>>[Usage of TF Variables](#scrollTo=2TubsFPeZ0Rz)

>>>[Initialize variables](#scrollTo=r9Xymzuia0j3)

>>>[Evaluate the values of variables](#scrollTo=239nTB8ScEMD)

>>[*Quiz 2](#scrollTo=lJ3XeX_Gn4a3)

>[3-2. Feeding Input Data into a Tensorflow Graph](#scrollTo=rgFhwdh4kJlB)

>>[Placeholder](#scrollTo=JNTEqevyzz2X)

>>[Dataset](#scrollTo=9mHYbZmS06zb)

>>[Create dataset from files using Dataset API](#scrollTo=hV-LVSuslOLE)

>>>[Create dummy binary files](#scrollTo=mCt7x4ByogNm)

>>>[FixedLengthRecordDataset : each fixed-length record is a data instance.](#scrollTo=0rBvsoONqBSl)

>>>[Create dummy text files](#scrollTo=L5FwnpyyneZQ)

>>>[TextLineDataset : each text line is a data instance.](#scrollTo=Jv2Vc8gt9WbO)

>>[Transform dataset](#scrollTo=S8eqeLjir-ar)

>>[Speed up Dataset processing](#scrollTo=gXqUUZeo5a9E)

>>[*Quiz 3](#scrollTo=fEs3qEJszYgu)

>[3-3. Logistic Regression](#scrollTo=z8oia-fDJ4cx)

>>[Download and Read MNIST data using the dataset API](#scrollTo=WYPbCvJxL8fH)

>>>[Build an input pipeline using the dataset API](#scrollTo=lq_2ypB720KU)

>>[Create weights and bias](#scrollTo=8H5Yn3pxNVOH)

>>[Build a logistic regression model](#scrollTo=wkJhz1tCNcih)

>>[Define a loss function](#scrollTo=6h4HwTbMNkx6)

>>[Define a training op](#scrollTo=nZDF4B7jN5r9)

>>[Train and calculate accuracy](#scrollTo=0BjGaGU4OM_O)



#3-1. TensorFlow Ops

## Graph and Session
**Graph** : It contains a set of Operations (units of computation) and Tensors (units of data between operations).

**Session** : It encapsulates an execution environment such as which operations are executed and what is the current values of Tensor objects. 

Let's learn Graph and Session using examples presented below.

## Constant Op

Let's create a constant in TensorFlow.

**```tf.constant(value, dtype = None, shape = None, name = 'Const', verify_shape = False)```**

In [0]:
import tensorflow as tf
import tensorflow.contrib.eager as tfe
tfe.enable_eager_execution()



In [4]:
graph = tf.Graph()
with graph.as_default():
  #constant of 1d tensor, or a vector
  a = tf.constant([2,2], name = 'vector')

  #constant of 2x2 tensor, or a matrix
  b = tf.constant([[0,2], [1,3]], name = 'matrix')

print(a)
print(b)

Tensor("vector:0", shape=(2,), dtype=int32)
Tensor("matrix:0", shape=(2, 2), dtype=int32)


In [5]:
# Get values of a and b
with tf.Session(graph=graph) as sess:
  print('a')
  print(sess.run(a))
  print('b')
  print(sess.run(b))

a
[2 2]
b
[[0 2]
 [1 3]]


## Math Ops
TensorFlow math ops are pretty standard. The following example shows a matrix division op.

In [6]:
graph = tf.Graph()
with graph.as_default():
  # Create constant a and b
  a = tf.constant([2,2], name = 'a', dtype = tf.float32)
  b = tf.constant([[0,1], [2,3]], name = 'b', dtype = tf.float32)
  
  # Create divide operation using b and a
  div = tf.div(b, a)

print('Print information of div op')
print(div.op)

print('\nPrint div')
print(div)

Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
Print information of div op
name: "div"
op: "RealDiv"
input: "b"
input: "a"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}


Print div
Tensor("div:0", shape=(2, 2), dtype=float32)


Run div operations.

In [7]:
with tf.Session(graph=graph) as sess:
  print('Print div.op')
  print(sess.run(div.op))
  
  print('\nPrint div')
  print(sess.run(div))

Print div.op
None

Print div
[[0.  0.5]
 [1.  1.5]]


## Quiz 1
**Define a graph with two constants with shape=[2, 2] and a matmul operation. Print the values of c.
(X: matrix multiplication, HINT: use tf.matmul) **

In [51]:
import tensorflow as tf

graph = tf.Graph()
t = tf.random_normal([2,2],mean=3)
sess = tf.Session()
sess.run(t)

array([[4.610576 , 2.0455003],
       [3.715271 , 3.11921  ]], dtype=float32)

In [57]:
import numpy as np
np.random.random(size=(2,2))

array([[0.59187775, 0.39972936],
       [0.85847551, 0.35101929]])

In [60]:
import tensorflow as tf
import numpy as np
graph = tf.Graph()
with graph.as_default():
  ############# Write here. ################
  a = tf.constant(np.random.random(size=(2,2)))
  b = tf.constant(np.random.random(size=(2,2)))
  c = tf.matmul(a,b)
  ##########################################

with tf.Session(graph=graph) as sess:
  print(sess.run(c))

[[0.23130782 0.69591677]
 [0.0959227  0.25833004]]


## Variables

TensorFlow object to store mutable data (e.g., model parameters).

### Creating variables

To declare a variable, you create an instance of the class tf.Variable. tf.constant is written as lowercase because it's an op, and tf.Variable is written with a capital "V" because it's a class with multiple ops.

#### Usage of TF Variables


```
x = tf.Variable(...)
x.initializer   #init
x.value         #read op
x.assign(...)   #write op
x.assign_add(...) # x+=...
```



The old way to create a variable is: 

**```tf.Variable(< initial-value >, name = < optional-name >)```**

Create three variables using `tf.Variable`

In [8]:
graph = tf.Graph()
with graph.as_default():
  # Create scalar variable
  s = tf.Variable(2, name = 'scalar')
  # Create matrix variable
  m = tf.Variable([[0,1], [2,3]], name = 'matrix')
  # Create zero matrix using tf.zeros
  W = tf.Variable(tf.zeros([784,10]))

Instructions for updating:
Colocations handled automatically by placer.


The new and encouraged way is **`tf.get_variable`**, which allows us to provide the variable's internal name, shape, type, and initializer to give the variable its initial value.

```
tf.get_variable(
    name,
    shape=None,
    dtype=None,
    initializer=None,
    regularizer=None,
    trainable=True,
    collections=None,
    caching_device=None,
    partitioner=None,
    validate_shape=True,
    use_resource=None,
    custom_getter=None,
    constraint=None
)
```

Create three variables using `tf.get_variable`

In [0]:
graph = tf.Graph()
with graph.as_default():
  s = tf.get_variable('scalar', initializer=tf.constant(2))
  m = tf.get_variable('matrix', initializer=tf.constant([[0,1], [2,3]]))
  W = tf.get_variable('big_matrix', shape=(784, 10), initializer=tf.zeros_initializer())

In [12]:
with tf.Session(graph=graph) as sess:
  #필수로 Variable 에 대해서는 initialize를 명시적으로 해줘야 실행 가능함
  init = tf.global_variables_initializer()
  sess.run(init)
  print(sess.run(s))
  print(sess.run(m))
  print(sess.run(W))

2
[[0 1]
 [2 3]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


### Initialize variables

Before using a variable, you must initialize it, or else you'll run into an error.

To initiliaze them all at once: use **`tf.global_variables_initializer()`**

In [0]:
with tf.Session(graph=graph) as sess:
  # Initialize variables
  sess.run(tf.global_variables_initializer())
  print('print s')
  print(sess.run(s))
  print('\nprint m')
  print(sess.run(m))
  print('\nprint W')
  print(sess.run(W))

print s
2

print m
[[0 1]
 [2 3]]

print W
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


### Evaluate values of variables

To get the value of a variable, we need to fetch it within a session.

This example shows how to evaluate the value (`sess.run` and `eval`).

In [18]:
with tf.Session() as sess:
  v = tf.get_variable('normal_matrix', shape=(784,10), initializer=tf.truncated_normal_initializer())
  sess.run(tf.global_variables_initializer())
  v.eval()

ValueError: ignored

In [13]:
graph = tf.Graph()
with graph.as_default():
  # v is a 784 x 10 variable of random values
  v = tf.get_variable('normal_matrix', shape=(784,10), initializer=tf.truncated_normal_initializer())

with tf.Session(graph=graph) as sess:
  # Initialize variables
  sess.run(tf.global_variables_initializer())
  
  # Get value with sess.run()
  v_sess = sess.run(v)
  print('v value with sess.run')
  print(v_sess)

  # Get value with v.eval()
  v_eval = v.eval()
  print('\nv value with v.eval()')
  print(v_eval)

v value with sess.run
[[ 1.2321249  -0.43968326  0.81738865 ... -0.5795666   0.15272485
   1.454538  ]
 [ 1.4339306   0.60545444  1.0215849  ...  0.7473966  -0.97005785
  -0.43987107]
 [ 1.7107915   0.59194946 -0.09696774 ...  1.3537883  -0.83571017
   0.37570116]
 ...
 [-0.11873318  1.0012013   0.95490146 ... -1.2887901  -0.6996174
   1.390105  ]
 [-0.482495   -0.23953633 -0.7638849  ... -0.6663543   0.16483837
  -1.4218045 ]
 [ 0.3522759  -0.8085719  -1.115115   ... -0.18757783 -0.79786646
   0.2702269 ]]

v value with v.eval()
[[ 1.2321249  -0.43968326  0.81738865 ... -0.5795666   0.15272485
   1.454538  ]
 [ 1.4339306   0.60545444  1.0215849  ...  0.7473966  -0.97005785
  -0.43987107]
 [ 1.7107915   0.59194946 -0.09696774 ...  1.3537883  -0.83571017
   0.37570116]
 ...
 [-0.11873318  1.0012013   0.95490146 ... -1.2887901  -0.6996174
   1.390105  ]
 [-0.482495   -0.23953633 -0.7638849  ... -0.6663543   0.16483837
  -1.4218045 ]
 [ 0.3522759  -0.8085719  -1.115115   ... -0.18757783 -

To change the values of variables, use `tf.assign`.

You can see variable v changes after an *assign* operation is executed.

In [16]:
graph = tf.Graph()
with graph.as_default():
  # Create variable v.
  v = tf.get_variable("a", shape=(2), initializer=tf.ones_initializer())
  
  # Create two assign operations.
  assign_2 = tf.assign(v, [2, 2])
  assign_5 = tf.assign(v, [5, 5])
  
with tf.Session(graph=graph) as sess:
  sess.run(tf.global_variables_initializer())
  
  # Before applying assign op.
  v_val = sess.run(v)
  print('Initial value: %s' % (v_val))
  
  # Run assign_2
  sess.run(assign_2)
  print('After assign_2: %s' % sess.run(v))
  
  # Run assign_5
  sess.run(assign_5)
  print('After assign_5: %s' % sess.run(v))

Initial value: [1. 1.]
After assign_2: [2. 2.]
After assign_5: [5. 5.]


## Quiz 2
** Define two variables (name : "variable1", "varaiable2") with shape = [2, 3]. Initialize the variables as zeros first. **

**Then, change the values of "variable1" as [[0,1,2], [3,4,5]]. Print final values of two variables. **

In [65]:
graph = tf.Graph()
with graph.as_default():
  ############# Write here. ################
  v1 = tf.Variable(tf.zeros([2,3]),name='variable1')
  v2 = tf.Variable(tf.zeros([2,3]),name='variable2')
  
  v1_assign = tf.assign(v1,[[0,1,2],[3,4,5]])
  ##########################################

with tf.Session(graph=graph) as sess:
  ############# Write here. ################
  init = tf.global_variables_initializer()
  sess.run(init)
  sess.run(v1_assign)
  
  print(sess.run([v1,v2]))
  ##########################################

[array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32), array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)]


# 3-2. Feeding Input Data into a Tensorflow Graph

How to feed data into a TensorFlow program?

Using `tf.Placeholder` or

**Using TensorFlow Dataset API (recommended)**

**Create dummy array: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]**

In [19]:
# Create 0~9 array
input_constant = [i for i in range(10)]
print('input_constant: %s' % input_constant)

input_constant: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


## Placeholder

TensorFlow provides a **placeholder** operation that must be fed with data on execution.

TensorFlow's feed mechanism lets you inject data into any Tensor in a computation graph.

A Python computation can thus feed data directly into the graph.

Supply feed data through the feed_dict argument to a run() or eval() call that initiates computation.

A placeholder exists solely to serve as the target of feeds. It is not initialized and contains no data.

A placeholder generates an error if it is executed without a feed, so you won't forget to feed it.

In [20]:
graph = tf.Graph()
with graph.as_default():
  # Create scalar placeholder with integer data type.
  a = tf.placeholder(shape=[], dtype=tf.int32)
  
  # Create add operation using placeholder.
  add_1 = tf.add(a, 1)
  
  with tf.Session(graph=graph) as sess:
    for i in range(10):
      # Make feed_dict where the key is placeholder and the value is the input data.
      feed_dict = {a: input_constant[i]}
      
      # Run operation with feeding data.
      print(sess.run(add_1, feed_dict=feed_dict))

1
2
3
4
5
6
7
8
9
10


## Dataset

The `tf.data` API is the most advanced API for writing TensorFlow input pipelines.

It allows you to build complex pipelines by composing simple building blocks. 

Two main abstractions introduced by the `tf.data` API are:
* `tf.data.Dataset`: contains a sequence of items (each item represents one or more `tf.Tensor`s)
* `tf.data.Iterator`: provides interface to iterate through the dataset

Users can create new Datasets from existing `tf.Tensor`s by using static methods like `Dataset.from_tensor_slices()`. 

For example, you can create a Dataset of string Tensors that represents input file names. 

Transformation of exisiting Datasets is another way of creating new dataset. 

TensorFlow provides frequently-used Dataset transformations such as `Dataset.batch` or `Dataset.shuffle` (please refer to https://www.tensorflow.org/api_docs/python/tf/data/Dataset). 

An Iterator is associated with a particular Dataset and we can retrieve the next element by executing an operation returned by `Iterator.get_next()`. 

This typically acts as an interface between your Dataset input pipline and your model.

The simplest way to construct an Iterator is using `Dataset.make_one_shot_iterator()`.



**`tf.data.Dataset.from_tensor_slices()`**

Creates a Dataset whose elements are slices of the given *python array* or *numpy array* or *tensors*.

In [23]:
ds = tf.data.Dataset.from_tensor_slices(input_constant)
ds

<DatasetV1Adapter shapes: (), types: tf.int32>

Create iterator using Dataset and run operation.

Using Dataset API, you do not need to feed input data.

In [24]:
graph = tf.Graph()
with graph.as_default():
  
  # Create iterator for dataset
  iterator = ds.make_one_shot_iterator()
  print(iterator)
  # Retrieve next element from iterator
  data_getter = iterator.get_next()
  print(data_getter)
  
  # Create add operation
  add_1 = tf.add(data_getter, 1)
  
  with tf.Session(graph=graph) as sess:
    for i in range(10):
      print(sess.run(add_1))

Tensor("IteratorGetNext:0", shape=(), dtype=int32)
1
2
3
4
5
6
7
8
9
10


## Create a dataset from files using the Dataset API

Define a helper function for reading the first three dataset instances.

In [0]:
def read_dataset_instance(ds, count=3):
  graph = tf.Graph()
  with graph.as_default():
    iterator = ds.make_one_shot_iterator()
    data_getter = iterator.get_next()

  with tf.Session(graph=graph) as sess:
    for i in range(count):
      data_instance = sess.run(data_getter)
      print('step %d data_instance_length: %d' % (i, len(data_instance)))
      print('step %d data_instance: %s' % (i, data_instance))

### Create dummy binary files

In [0]:
import os
import numpy as np

def create_bin_file(index):
  with open('binary_file_%d'%index, 'wb') as f:
    f.write(np.full((100), index))
    
bin_filenames = []
for i in range(3):
  create_bin_file(i)
  bin_filenames.append('binary_file_%d'% i)

### FixedLengthRecordDataset : each fixed-length record is a data instance.

In this example, each data instance is a 8-byte integer.

In [27]:
#어떤 길이로 데이터를 잘라서 읽어들일것인지 parameter로 넘겨줌
ds = tf.data.FixedLengthRecordDataset(bin_filenames, 8)
read_dataset_instance(ds)

step 0 data_instance_length: 8
step 0 data_instance: b'\x00\x00\x00\x00\x00\x00\x00\x00'
step 1 data_instance_length: 8
step 1 data_instance: b'\x00\x00\x00\x00\x00\x00\x00\x00'
step 2 data_instance_length: 8
step 2 data_instance: b'\x00\x00\x00\x00\x00\x00\x00\x00'


### Create dummy text files

In [0]:
def create_text_file(index):
  with open('text_file_%d'%index, 'w') as f:
    f.write('hello_%d\n'%index)
    f.write('TensorFlow_%d\n'%index)

text_filenames = []
for i in range(3):
  create_text_file(i)
  text_filenames.append('text_file_%d'% i)

In [40]:
for f in text_filenames:
  with open(f,'r') as fr:
    print(fr.read())

hello_0
TensorFlow_0

hello_1
TensorFlow_1

hello_2
TensorFlow_2



### TextLineDataset : each text line is a data instance.


In [29]:
ds = tf.data.TextLineDataset(text_filenames)

read_dataset_instance(ds)

step 0 data_instance_length: 7
step 0 data_instance: b'hello_0'
step 1 data_instance_length: 12
step 1 data_instance: b'TensorFlow_0'
step 2 data_instance_length: 7
step 2 data_instance: b'hello_1'


## Transform dataset

**ds.shffule(buffer_size)**

shuffle: shuffle data instances randomly. buffer size represents the number of data instances to be sampled.


ds.shuffle with N > 1 can pick data instances randomly within N samples.

In [31]:
ds = tf.data.TextLineDataset(text_filenames)
ds = ds.shuffle(5)

read_dataset_instance(ds)

step 0 data_instance_length: 12
step 0 data_instance: b'TensorFlow_1'
step 1 data_instance_length: 7
step 1 data_instance: b'hello_1'
step 2 data_instance_length: 7
step 2 data_instance: b'hello_2'


ds.shuffle with N == 1 has the same effect with no shuffling.

In [0]:
ds = tf.data.TextLineDataset(text_filenames)
ds = ds.shuffle(1)

read_dataset_instance(ds)

step 0 data_instance_length: 7
step 0 data_instance: b'hello_0'
step 1 data_instance_length: 12
step 1 data_instance: b'TensorFlow_0'
step 2 data_instance_length: 7
step 2 data_instance: b'hello_1'


**ds.repeat(count)**

Repeat the data instances count times. 

Without ds.repeat(), an error is raised after reading all the data instances once.

In [32]:
ds = tf.data.TextLineDataset(text_filenames)
#100개의 instance 가 없어서 에러발생
read_dataset_instance(ds, 100)

step 0 data_instance_length: 7
step 0 data_instance: b'hello_0'
step 1 data_instance_length: 12
step 1 data_instance: b'TensorFlow_0'
step 2 data_instance_length: 7
step 2 data_instance: b'hello_1'
step 3 data_instance_length: 12
step 3 data_instance: b'TensorFlow_1'
step 4 data_instance_length: 7
step 4 data_instance: b'hello_2'
step 5 data_instance_length: 12
step 5 data_instance: b'TensorFlow_2'


OutOfRangeError: ignored

ds.repeat() can solve the error.

In [33]:
ds = tf.data.TextLineDataset(text_filenames)
ds = ds.repeat(100)

read_dataset_instance(ds, 100)

step 0 data_instance_length: 7
step 0 data_instance: b'hello_0'
step 1 data_instance_length: 12
step 1 data_instance: b'TensorFlow_0'
step 2 data_instance_length: 7
step 2 data_instance: b'hello_1'
step 3 data_instance_length: 12
step 3 data_instance: b'TensorFlow_1'
step 4 data_instance_length: 7
step 4 data_instance: b'hello_2'
step 5 data_instance_length: 12
step 5 data_instance: b'TensorFlow_2'
step 6 data_instance_length: 7
step 6 data_instance: b'hello_0'
step 7 data_instance_length: 12
step 7 data_instance: b'TensorFlow_0'
step 8 data_instance_length: 7
step 8 data_instance: b'hello_1'
step 9 data_instance_length: 12
step 9 data_instance: b'TensorFlow_1'
step 10 data_instance_length: 7
step 10 data_instance: b'hello_2'
step 11 data_instance_length: 12
step 11 data_instance: b'TensorFlow_2'
step 12 data_instance_length: 7
step 12 data_instance: b'hello_0'
step 13 data_instance_length: 12
step 13 data_instance: b'TensorFlow_0'
step 14 data_instance_length: 7
step 14 data_instance:

**ds.batch(batch_size)**

Combines data instances of this dataset into batches. batch_size represents the number of data instances to combine.

Make batches with batch size of 3

In [34]:
ds = tf.data.TextLineDataset(text_filenames)
ds = ds.shuffle(3)
ds = ds.repeat()
ds = ds.batch(3)

read_dataset_instance(ds)

step 0 data_instance_length: 3
step 0 data_instance: [b'hello_0' b'hello_1' b'hello_2']
step 1 data_instance_length: 3
step 1 data_instance: [b'TensorFlow_2' b'TensorFlow_0' b'TensorFlow_1']
step 2 data_instance_length: 3
step 2 data_instance: [b'TensorFlow_0' b'TensorFlow_1' b'hello_2']


**ds.map(fn)**

apply fn to each data instance in the dataset

Apply split_index function to the batched dataset

In [39]:
def split_index(data):
  data = tf.split(data, [1, 1, 1])
  return tf.strings.join(data, '+')

ds = tf.data.TextLineDataset(text_filenames)
ds = ds.shuffle(5)
ds = ds.repeat()
ds = ds.batch(3)
ds = ds.map(split_index)

read_dataset_instance(ds)

step 0 data_instance_length: 1
step 0 data_instance: [b'hello_0+TensorFlow_1+hello_1']
step 1 data_instance_length: 1
step 1 data_instance: [b'TensorFlow_2+TensorFlow_0+hello_2']
step 2 data_instance_length: 1
step 2 data_instance: [b'hello_2+TensorFlow_2+hello_0']


##  Speed up Dataset processing



**ds.interleave(map_func, cycle_length)**

map _func : map function to apply to each data instance

cycle_length : the number of data instances to process concurrently

Read files concurrently 

In [36]:
ds = tf.data.Dataset.from_tensor_slices(text_filenames)
ds = ds.apply(
      tf.contrib.data.parallel_interleave(
          lambda filename: tf.data.TextLineDataset(filename),
          cycle_length=len(text_filenames)))

read_dataset_instance(ds)

Instructions for updating:
Use `tf.data.experimental.parallel_interleave(...)`.
step 0 data_instance_length: 7
step 0 data_instance: b'hello_0'
step 1 data_instance_length: 7
step 1 data_instance: b'hello_1'
step 2 data_instance_length: 7
step 2 data_instance: b'hello_2'


**ds.prefetch(buffer_size)** 

prefetch elements from a dataset. buffer size represents the maximum buffer size

Prefetch five data instances

In [37]:
ds = tf.data.Dataset.from_tensor_slices(text_filenames)
ds = ds.apply(
      tf.contrib.data.parallel_interleave(
          lambda filename: tf.data.TextLineDataset(filename),
          cycle_length=len(text_filenames)))
ds = ds.prefetch(5)

read_dataset_instance(ds)

step 0 data_instance_length: 7
step 0 data_instance: b'hello_0'
step 1 data_instance_length: 7
step 1 data_instance: b'hello_1'
step 2 data_instance_length: 7
step 2 data_instance: b'hello_2'


## Quiz 3
**Create a dataset following the instructions**
1. Create a textline dataset using `ex_filenames`. 
2. Shuffle the dataset with buffer size 10.
3. Repeat the dataset.
4. Convert each data instance using the `cast` function.
5. Make the data instances as a batch (batch size = 3).



In [68]:
import random

def create_text_file(index):
  with open('ex_file_%d'%index, 'w') as f:
    for i in range(5):
      f.write('%d\n' % random.randrange(0,index+1))
    
ex_filenames = []
for i in range(3):
  create_text_file(i)
  ex_filenames.append('ex_file_%d'% i)

def cast(data):
  data = tf.strings.to_number(data, out_type=tf.int32)
  return data

############# Write here. ################
ds = tf.data.TextLineDataset(ex_filenames)
ds = ds.shuffle(10)
ds = ds.repeat()
ds = ds.batch(3)
ds = ds.map(cast)

##########################################

graph = tf.Graph()
with graph.as_default():
  iterator = ds.make_one_shot_iterator()
  data_getter = iterator.get_next()

with tf.Session(graph=graph) as sess:
  data_instance = sess.run(data_getter)
  print(data_instance)

[0 0 0]


# 3-3. Logistic Regression

Now, we can build a logistic regression example on TensorFlow by following the steps below.

**1.Download and Read MNIST data using the dataset API**

**2. Create weights and biases**

**3. Build a logistic regression model**

**4. Define a loss function**

**5. Define a training op**

**6. Train and calculate accuracy**

## Download and Read MNIST data using the dataset API

In [41]:
#@title Download the MNIST dataset
import tensorflow

from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('data/mnist', one_hot = True)    # if "MNIST/data" does not work, try "data/mnist"

import os
import gzip
import shutil
import struct
import urllib
import time

os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

from matplotlib import pyplot as plt
import numpy as np
import tensorflow as tf

def huber_loss(labels, predictions, delta=14.0):
    residual = tf.abs(labels - predictions)
    def f1(): return 0.5 * tf.square(residual)
    def f2(): return delta * residual - 0.5 * tf.square(delta)
    return tf.cond(residual < delta, f1, f2)

def safe_mkdir(path):
    """ Create a directory if there isn't one already. """
    try:
        os.mkdir(path)
    except OSError:
        pass

def read_birth_life_data(filename):
    """
    Read in birth_life_2010.txt and return:
    data in the form of NumPy array
    n_samples: number of samples
    """
    text = open(filename, 'r').readlines()[1:]
    data = [line[:-1].split('\t') for line in text]
    births = [float(line[1]) for line in data]
    lifes = [float(line[2]) for line in data]
    data = list(zip(births, lifes))
    n_samples = len(data)
    data = np.asarray(data, dtype=np.float32)
    return data, n_samples

def download_one_file(download_url, 
                    local_dest, 
                    expected_byte=None, 
                    unzip_and_remove=False):
    """ 
    Download the file from download_url into local_dest
    if the file doesn't already exists.
    If expected_byte is provided, check if 
    the downloaded file has the same number of bytes.
    If unzip_and_remove is True, unzip the file and remove the zip file
    """
    if os.path.exists(local_dest) or os.path.exists(local_dest[:-3]):
        print('%s already exists' %local_dest)
    else:
        print('Downloading %s' %download_url)
        local_file, _ = urllib.request.urlretrieve(download_url, local_dest)
        file_stat = os.stat(local_dest)
        if expected_byte:
            if file_stat.st_size == expected_byte:
                print('Successfully downloaded %s' %local_dest)
                if unzip_and_remove:
                    with gzip.open(local_dest, 'rb') as f_in, open(local_dest[:-3],'wb') as f_out:
                        shutil.copyfileobj(f_in, f_out)
                    os.remove(local_dest)
            else:
                print('The downloaded file has unexpected number of bytes')

def download_mnist(path):
    """ 
    Download and unzip the dataset mnist if it's not already downloaded 
    Download from http://yann.lecun.com/exdb/mnist
    """
    safe_mkdir(path)
    url = 'http://yann.lecun.com/exdb/mnist'
    filenames = ['train-images-idx3-ubyte.gz',
                'train-labels-idx1-ubyte.gz',
                't10k-images-idx3-ubyte.gz',
                't10k-labels-idx1-ubyte.gz']
    expected_bytes = [9912422, 28881, 1648877, 4542]

    for filename, byte in zip(filenames, expected_bytes):
        download_url = os.path.join(url, filename)
        local_dest = os.path.join(path, filename)
        download_one_file(download_url, local_dest, byte, True)

# Parse each MNIST data instance as images and labels
def parse_data(path, dataset, flatten):
    if dataset != 'train' and dataset != 't10k':
        raise NameError('dataset must be train or t10k')

    label_file = os.path.join(path, dataset + '-labels-idx1-ubyte')
    with open(label_file, 'rb') as file:
        _, num = struct.unpack(">II", file.read(8))
        labels = np.fromfile(file, dtype=np.int8) #int8
        new_labels = np.zeros((num, 10))
        new_labels[np.arange(num), labels] = 1
    
    img_file = os.path.join(path, dataset + '-images-idx3-ubyte')
    with open(img_file, 'rb') as file:
        _, num, rows, cols = struct.unpack(">IIII", file.read(16))
        imgs = np.fromfile(file, dtype=np.uint8).reshape(num, rows, cols) #uint8
        imgs = imgs.astype(np.float32) / 255.0
        if flatten:
            imgs = imgs.reshape([num, -1])

    return imgs, new_labels
  
# Read in the mnist dataset, given that the data is stored in path
# Return two tuples of numpy arrays
# ((train_imgs, train_labels), (test_imgs, test_labels))
def read_mnist(path, flatten=True, num_train=55000):
    imgs, labels = parse_data(path, 'train', flatten)
    indices = np.random.permutation(labels.shape[0])
    train_idx, val_idx = indices[:num_train], indices[num_train:]
    train_img, train_labels = imgs[train_idx, :], labels[train_idx, :]
    val_img, val_labels = imgs[val_idx, :], labels[val_idx, :]
    test = parse_data(path, 't10k', flatten)
    return (train_img, train_labels), (val_img, val_labels), test

mnist_folder = "data/mnist-"
download_mnist(mnist_folder)
train, val, test = read_mnist(mnist_folder, flatten=True)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use urllib or similar directly.
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting data/mnist/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting data/mnist/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting data/mnist/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting data/mnist/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py fr

### Build an input pipeline using the dataset API
Create datasets from numpy arrays created by reading the MNIST dataset files. 

Then, make them as batches with batch size of 128.

In [42]:
train

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[1., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.]]))

In [0]:
batch_size = 128

graph = tf.Graph()
with graph.as_default():
  # data created above by the following method
  # train, val, test = read_mnist(mnist_folder, flatten=True)
  train_data = tf.data.Dataset.from_tensor_slices(train)
  train_data = train_data.shuffle(10000)
  train_data = train_data.batch(batch_size)

  test_data = tf.data.Dataset.from_tensor_slices(test)
  test_data = test_data.batch(batch_size)

  iterator = tf.data.Iterator.from_structure(train_data.output_types, train_data.output_shapes)
  img, label = iterator.get_next()

  train_init = iterator.make_initializer(train_data) #initializer for train_data
  test_init = iterator.make_initializer(test_data) #initializer for test_data

## Create weights and bias
w is initialized to random normal distribution variables with mean 0 and standard deviation 0.01. b is initialized to 0's. The shape of w depends on the dimensions of X and Y so that Y = tf.matmul(X,w). The shape of b depends on Y.

In [0]:
with graph.as_default():
  w = tf.get_variable(name='weights_dataset', shape=(784, 10), initializer=tf.random_normal_initializer(0, 0.01))
  b = tf.get_variable(name='bias_dataset', shape=(1, 10), initializer=tf.zeros_initializer())

## Build a logistic regression model

This model returns logits that will be passed into the softmax layer.

In [0]:
with graph.as_default():
  logits = tf.matmul(img, w) + b

## Define a loss function

The cross entropy of softmax of logits is our loss function.

In [0]:
with graph.as_default():
  entropy = tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits, labels=label, name='entropy')
  loss = tf.reduce_mean(entropy, name='loss') # average over all the examples in the batch

## Define a training op

We'll use an Adam optimizer with a learning rate of 0.01 to minimize loss.

In [0]:
with graph.as_default():
  optimizer = tf.train.AdamOptimizer(0.01)
  train_op = optimizer.minimize(loss)

## Train and calculate accuracy

Finally, we train the model and use the test set to calculate the accuracy of our model.

In [48]:
with graph.as_default():
  preds = tf.nn.softmax(logits)
  correct_preds = tf.equal(tf.argmax(preds, 1), tf.argmax(label, 1))
  accuracy = tf.reduce_sum(tf.cast(correct_preds, tf.float32))

with tf.Session(graph=graph) as sess:
   
    start_time = time.time()
    sess.run(tf.global_variables_initializer())

    # train the model n_epochs times
    for i in range(30): 	
        sess.run(train_init)	# initialize training dataset iterator
        total_loss = 0
        n_batches = 0
        try:
            while True:
                _, l = sess.run([train_op, loss])
                total_loss += l
                n_batches += 1
        except tf.errors.OutOfRangeError:
            pass
        print('Average loss epoch {0}: {1}'.format(i, total_loss/n_batches))        
    print('Total time: {0} seconds'.format(time.time() - start_time))


    # test the model
    sess.run(test_init)			# initialize test dataset iterator
    total_correct_preds = 0
    try:
        while True:
            accuracy_batch = sess.run(accuracy)
            total_correct_preds += accuracy_batch
    except tf.errors.OutOfRangeError:
        pass
    print('Accuracy {0}'.format(total_correct_preds/10000))

Average loss epoch 0: 0.3668336667293726
Average loss epoch 1: 0.29454850987639536
Average loss epoch 2: 0.28413341130281605
Average loss epoch 3: 0.27795317228450334
Average loss epoch 4: 0.2754930011061735
Average loss epoch 5: 0.2710635873294154
Average loss epoch 6: 0.2696129959856355
Average loss epoch 7: 0.2703531366967878
Average loss epoch 8: 0.2632993358858796
Average loss epoch 9: 0.2643631101001141
Average loss epoch 10: 0.2641341299684935
Average loss epoch 11: 0.2619624991056531
Average loss epoch 12: 0.2590268860895966
Average loss epoch 13: 0.26181176800367445
Average loss epoch 14: 0.2575613180218741
Average loss epoch 15: 0.25733905547233515
Average loss epoch 16: 0.25472047051718066
Average loss epoch 17: 0.25659440840746084
Average loss epoch 18: 0.2555305506081082
Average loss epoch 19: 0.2545956387422806
Average loss epoch 20: 0.25689747330061224
Average loss epoch 21: 0.25524225801576017
Average loss epoch 22: 0.25486626663180284
Average loss epoch 23: 0.253238767